// @generated by tools/gen_songs.py from songs/*.json — DO NOT EDIT.
// Re-run `make gen-songs` after editing the JSON.
//
// Songs in `SONGS` order (songs/index.json); see docs/SONGS_FORMAT.md for the
// contract and src/audio/songs.rs for the types.
#![allow(clippy::all)]
#![allow(clippy::excessive_precision)]
// Not every song set uses every scale / drum the types offer.
#![allow(unused_imports)]

use super::songs::{
    Drum::{self, Hat, Kick, Silent, Snare},
    Scale, Section, SongSpec, Wave, DORIAN, HARMONIC_MINOR, LOCRIAN, MINOR, PHRYGIAN,
    PHRYGIAN_DOMINANT, REST,
};

// ---- insert_coin.json: "Insert Coin" -----------------------------------------------------------
//
// SONG 1 — "Insert Coin" (WAVY): ominous, dreamy title theme. A-minor, slow,
// soft triangle/sine voices, lush pad, sparse falling arp. The calm before it.

const INSERT_COIN_INTRO: Section = Section {
    label: "intro",
    bass: &[
        0, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
    ],
    lead: &[
        REST, REST, REST, REST, REST, REST, 14, REST, REST, REST, REST, REST, 12, REST, REST, REST,
        REST, REST, REST, REST, REST, REST, 11, REST, REST, REST, REST, REST, 9, REST, REST, REST,
    ],
    pad: &[
        0, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
    ],
    arp: &[
        REST, REST, REST, REST, 7, REST, 9, REST, REST, REST, REST, REST, 11, REST, 9, REST,
        REST, REST, REST, REST, 9, REST, 11, REST, REST, REST, REST, REST, 12, REST, 9, REST,
    ],
    drums: &[
        Silent, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Hat, Silent, Silent, Silent,
    ],
};
const INSERT_COIN_VERSE: Section = Section {
    label: "verse",
    bass: &[0, REST, REST, REST, REST, REST, REST, REST, 3, REST, REST, REST, REST, REST, REST, REST],
    lead: &[
        REST, REST, 14, REST, REST, REST, 12, REST, REST, REST, 11, REST, REST, REST, REST, REST,
        REST, REST, 12, REST, REST, REST, 10, REST, REST, REST, 9, REST, REST, REST, 7, REST,
    ],
    pad: &[
        7, REST, REST, REST, REST, REST, REST, REST, 10, REST, REST, REST, REST, REST, REST, REST,
    ],
    arp: &[
        REST, REST, REST, REST, 7, REST, 9, REST, REST, REST, REST, REST, 11, REST, 9, REST,
        REST, REST, REST, REST, 9, REST, 11, REST, REST, REST, REST, REST, 12, REST, 9, REST,
    ],
    drums: &[
        Silent, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Hat, Silent, Silent, Silent,
    ],
};
const INSERT_COIN_REFRAIN: Section = Section {
    label: "refrain",
    bass: &[0, REST, REST, REST, 0, REST, 3, REST, 5, REST, REST, REST, 3, REST, 2, REST],
    lead: &[
        7, REST, 9, REST, 11, REST, 12, REST, REST, 14, REST, 12, 11, REST, 9, REST,
        7, REST, 9, REST, 11, REST, 14, REST, REST, 16, REST, 14, 12, REST, 11, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 3, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        14, 16, 18, 16, 14, 16, 18, 21, 14, 16, 18, 16, 18, 16, 14, 11,
        14, 16, 18, 21, 18, 16, 14, 16, 18, 21, 23, 21, 18, 16, 14, 12,
    ],
    drums: &[
        Kick, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Snare, Silent, Hat, Silent,
    ],
};
const INSERT_COIN_BRIDGE: Section = Section {
    label: "bridge",
    bass: &[5, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    lead: &[
        REST, REST, REST, REST, REST, REST, REST, REST, 11, REST, REST, REST, 9, REST, 7, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, 12, REST, REST, REST, 10, REST, 9, REST,
    ],
    pad: &[5, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        7, REST, 9, REST, 11, REST, 9, REST, 7, REST, 9, REST, 11, REST, 14, REST,
        11, REST, 9, REST, 7, REST, 9, REST, 11, REST, 9, REST, 7, REST, 4, REST,
    ],
    drums: &[
        Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Silent, Silent, Silent, Silent,
    ],
};
pub const INSERT_COIN: SongSpec = SongSpec {
    name: "Insert Coin",
    root: 55.0, // A1
    scale: MINOR,
    bpm: 84.0,
    steps_per_beat: 4,
    bass_wave: Wave::Triangle,
    lead_wave: Wave::Sine,
    pad_wave: Wave::Triangle,
    arp_wave: Wave::Sine,
    sections: &[
        INSERT_COIN_INTRO,
        INSERT_COIN_VERSE,
        INSERT_COIN_VERSE,
        INSERT_COIN_REFRAIN,
        INSERT_COIN_VERSE,
        INSERT_COIN_BRIDGE,
        INSERT_COIN_REFRAIN,
        INSERT_COIN_REFRAIN,
    ],
    intensity: 0.5,
};

// ---- neon_lounge.json: "Neon Lounge" -----------------------------------------------------------
//
// SONG 2 — "Neon Lounge" (WAVY): cool, loungey opening groove. A-minor,
// laid-back, mellow syncopated lead over light hats — neon at dusk.

const NEON_LOUNGE_INTRO: Section = Section {
    label: "intro",
    bass: &[0, REST, REST, REST, REST, REST, REST, REST, 3, REST, REST, REST, REST, REST, REST, REST],
    lead: &[
        REST, REST, REST, REST, 7, REST, 9, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, 11, REST, 9, REST, REST, REST, REST, REST, REST, REST, REST, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 3, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        REST, 14, REST, 16, REST, 14, REST, 11, REST, 14, REST, 16, REST, 18, REST, 16,
        REST, 14, REST, 16, REST, 14, REST, 11, REST, 14, REST, 16, REST, 18, REST, 16,
    ],
    drums: &[
        Kick, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Silent, Silent, Hat, Silent,
    ],
};
const NEON_LOUNGE_VERSE: Section = Section {
    label: "verse",
    bass: &[0, REST, REST, REST, 0, REST, 4, REST, 3, REST, REST, REST, 2, REST, 2, REST],
    lead: &[
        7, REST, 9, REST, REST, 11, REST, 7, REST, REST, 9, REST, 10, REST, REST, REST,
        7, REST, 9, REST, REST, 11, REST, 12, REST, REST, 10, REST, 9, REST, 7, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 3, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        REST, 14, REST, 16, REST, 14, REST, 11, REST, 14, REST, 16, REST, 18, REST, 16,
        REST, 16, REST, 18, REST, 16, REST, 14, REST, 16, REST, 18, REST, 21, REST, 18,
    ],
    drums: &[
        Kick, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Silent, Silent, Hat, Snare,
    ],
};
const NEON_LOUNGE_REFRAIN: Section = Section {
    label: "refrain",
    bass: &[0, REST, 0, REST, 4, REST, 4, REST, 3, REST, 3, REST, 2, REST, 5, REST],
    lead: &[
        11, REST, 12, REST, 14, REST, 12, REST, 11, REST, 9, REST, 7, REST, 9, REST,
        11, REST, 12, REST, 14, REST, 16, REST, 14, REST, 12, REST, 11, REST, 9, REST,
    ],
    pad: &[3, REST, REST, REST, REST, REST, REST, REST, 5, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        18, 16, 14, 16, 18, 16, 14, 11, 18, 16, 14, 16, 18, 21, 18, 16,
        14, 16, 18, 21, 18, 16, 14, 16, 18, 21, 23, 21, 18, 16, 14, 12,
    ],
    drums: &[
        Kick, Silent, Hat, Snare, Silent, Silent, Hat, Silent, Kick, Silent, Hat, Snare, Silent, Silent, Hat, Snare,
    ],
};
const NEON_LOUNGE_BRIDGE: Section = Section {
    label: "bridge",
    bass: &[5, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    lead: &[
        REST, REST, 9, REST, 7, REST, REST, REST, REST, REST, 11, REST, 9, REST, REST, REST,
        REST, REST, 9, REST, 7, REST, REST, REST, REST, REST, 12, REST, 10, REST, 9, REST,
    ],
    pad: &[5, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        14, REST, 16, REST, 18, REST, 16, REST, 14, REST, 16, REST, 18, REST, 21, REST,
        18, REST, 16, REST, 14, REST, 16, REST, 14, REST, 11, REST, 9, REST, 7, REST,
    ],
    drums: &[
        Kick, Silent, Silent, Silent, Silent, Silent, Hat, Silent, Kick, Silent, Silent, Silent, Silent, Silent, Hat, Silent,
    ],
};
pub const NEON_LOUNGE: SongSpec = SongSpec {
    name: "Neon Lounge",
    root: 55.0, // A1
    scale: MINOR,
    bpm: 108.0,
    steps_per_beat: 4,
    bass_wave: Wave::Triangle,
    lead_wave: Wave::Triangle,
    pad_wave: Wave::Sawtooth,
    arp_wave: Wave::Triangle,
    sections: &[
        NEON_LOUNGE_INTRO,
        NEON_LOUNGE_VERSE,
        NEON_LOUNGE_VERSE,
        NEON_LOUNGE_REFRAIN,
        NEON_LOUNGE_VERSE,
        NEON_LOUNGE_BRIDGE,
        NEON_LOUNGE_REFRAIN,
        NEON_LOUNGE_REFRAIN,
    ],
    intensity: 0.55,
};

// ---- chrome_veins.json: "Chrome Veins" ---------------------------------------------------------
//
// SONG 3 — "Chrome Veins" (AGGRESSIVE): chromed, forward-leaning drive. B
// Dorian, pulsing square bass, bright square arp, warm saw pad. City blur.

const CHROME_VEINS_INTRO: Section = Section {
    label: "intro",
    bass: &[0, REST, REST, REST, 7, REST, REST, REST, 0, REST, REST, REST, 5, REST, 3, REST],
    lead: &[
        REST, REST, REST, REST, REST, REST, 7, REST, REST, REST, REST, REST, REST, REST, 9, REST,
        REST, REST, REST, REST, REST, REST, 11, REST, REST, REST, REST, REST, REST, REST, 7, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        14, 16, 18, 16, 14, 16, 18, 21, 14, 16, 18, 16, 18, 16, 14, 11,
        14, 16, 18, 16, 14, 16, 18, 21, 14, 16, 18, 16, 18, 16, 14, 11,
    ],
    drums: &[
        Kick, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Silent, Silent, Hat, Silent,
    ],
};
const CHROME_VEINS_VERSE: Section = Section {
    label: "verse",
    bass: &[0, REST, 0, REST, 7, REST, 0, REST, 0, REST, 0, REST, 5, REST, 3, REST],
    lead: &[
        REST, REST, 7, REST, 9, REST, 11, REST, REST, 12, REST, 11, 9, REST, 7, REST,
        REST, REST, 7, REST, 9, REST, 12, REST, REST, 14, REST, 12, 11, REST, 9, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        14, 16, 18, 16, 14, 16, 18, 21, 14, 16, 18, 16, 18, 16, 14, 11,
        14, 16, 18, 21, 18, 16, 14, 16, 18, 21, 23, 21, 18, 16, 14, 11,
    ],
    drums: &[
        Kick, Silent, Hat, Silent, Snare, Silent, Hat, Silent, Kick, Silent, Hat, Kick, Snare, Silent, Hat, Silent,
    ],
};
const CHROME_VEINS_REFRAIN: Section = Section {
    label: "refrain",
    bass: &[0, REST, 0, 7, 0, REST, 0, 7, 5, REST, 5, REST, 3, REST, 3, REST],
    lead: &[
        12, REST, 11, REST, 9, REST, 7, REST, 9, REST, 11, REST, 12, REST, 14, REST,
        16, REST, 14, REST, 12, REST, 11, REST, 9, REST, 11, REST, 12, REST, 14, REST,
    ],
    pad: &[3, REST, REST, REST, REST, REST, REST, REST, 7, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        18, 16, 14, 16, 18, 21, 18, 16, 14, 16, 18, 21, 23, 21, 18, 16,
        14, 16, 18, 21, 23, 21, 18, 16, 18, 21, 23, 26, 23, 21, 18, 16,
    ],
    drums: &[
        Kick, Hat, Hat, Silent, Snare, Silent, Hat, Kick, Kick, Hat, Hat, Kick, Snare, Silent, Hat, Snare,
    ],
};
const CHROME_VEINS_BRIDGE: Section = Section {
    label: "bridge",
    bass: &[5, REST, REST, REST, 5, REST, REST, REST, 4, REST, REST, REST, 4, REST, REST, REST],
    lead: &[
        REST, REST, 12, REST, 11, REST, 9, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, 14, REST, 12, REST, 11, REST, REST, REST, REST, REST, REST, REST, REST, REST,
    ],
    pad: &[5, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        14, REST, 16, REST, 18, REST, 16, REST, 14, REST, 16, REST, 18, REST, 21, REST,
        18, REST, 16, REST, 14, REST, 16, REST, 18, REST, 14, REST, 11, REST, 9, REST,
    ],
    drums: &[
        Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Hat, Silent,
    ],
};
pub const CHROME_VEINS: SongSpec = SongSpec {
    name: "Chrome Veins",
    root: 61.74, // B1
    scale: DORIAN,
    bpm: 118.0,
    steps_per_beat: 4,
    bass_wave: Wave::Square,
    lead_wave: Wave::Sawtooth,
    pad_wave: Wave::Sawtooth,
    arp_wave: Wave::Square,
    sections: &[
        CHROME_VEINS_INTRO,
        CHROME_VEINS_VERSE,
        CHROME_VEINS_VERSE,
        CHROME_VEINS_REFRAIN,
        CHROME_VEINS_VERSE,
        CHROME_VEINS_BRIDGE,
        CHROME_VEINS_REFRAIN,
        CHROME_VEINS_REFRAIN,
    ],
    intensity: 0.72,
};

// ---- descent.json: "Descent" -------------------------------------------------------------------
//
// SONG 4 — "Descent" (AGGRESSIVE): tense mid-descent. D Phrygian (flat 2nd),
// driving square bass hammering the root, restless saw arp, four-on-the-floor.

const DESCENT_INTRO: Section = Section {
    label: "intro",
    bass: &[0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST],
    lead: &[
        REST, REST, REST, REST, REST, REST, REST, REST, 7, REST, 8, REST, 10, REST, 8, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, 7, REST, 10, REST, 8, REST, 7, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 5, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        14, REST, 15, REST, 17, REST, 15, REST, 14, REST, 17, REST, 19, REST, 17, REST,
        14, REST, 15, REST, 17, REST, 15, REST, 14, REST, 17, REST, 19, REST, 17, REST,
    ],
    drums: &[
        Kick, Silent, Hat, Silent, Snare, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Snare, Silent, Hat, Silent,
    ],
};
const DESCENT_VERSE: Section = Section {
    label: "verse",
    bass: &[0, REST, 0, REST, 0, REST, 0, REST, 0, REST, 0, REST, 5, REST, 4, REST],
    lead: &[
        7, 8, 10, 8, 7, 10, 8, 10, 12, 11, 10, 8, 7, 8, 7, REST,
        7, 8, 10, 8, 10, 11, 12, 10, 8, 10, 12, 11, 10, 8, 7, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 5, REST, REST, REST, 4, REST, REST, REST],
    arp: &[
        14, REST, 15, REST, 17, REST, 15, REST, 14, REST, 17, REST, 19, REST, 17, REST,
        14, REST, 17, REST, 19, REST, 17, REST, 15, REST, 17, REST, 15, REST, 14, REST,
    ],
    drums: &[Kick, Hat, Hat, Hat, Snare, Hat, Hat, Hat, Kick, Hat, Kick, Hat, Snare, Hat, Hat, Hat],
};
const DESCENT_REFRAIN: Section = Section {
    label: "refrain",
    bass: &[0, 0, REST, 0, 0, 0, REST, 0, 0, 0, REST, 0, 5, REST, 4, REST],
    lead: &[
        12, REST, 11, REST, 10, REST, 8, REST, 7, REST, 8, REST, 10, REST, 12, REST,
        14, REST, 12, REST, 11, REST, 10, REST, 8, REST, 10, REST, 12, REST, 14, REST,
    ],
    pad: &[5, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        17, REST, 19, REST, 21, REST, 19, REST, 17, REST, 19, REST, 22, REST, 19, REST,
        21, REST, 22, REST, 24, REST, 22, REST, 19, REST, 17, REST, 15, REST, 14, REST,
    ],
    drums: &[
        Kick, Hat, Snare, Hat, Kick, Hat, Snare, Hat, Kick, Kick, Snare, Hat, Kick, Snare, Snare, Hat,
    ],
};
const DESCENT_BRIDGE: Section = Section {
    label: "bridge",
    bass: &[5, REST, REST, REST, 5, REST, REST, REST, 4, REST, REST, REST, 4, REST, REST, REST],
    lead: &[
        REST, REST, 10, REST, 8, REST, 7, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, 12, REST, 10, REST, 8, REST, REST, REST, REST, REST, REST, REST, REST, REST,
    ],
    pad: &[5, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        14, REST, 15, REST, 17, REST, 15, REST, 14, REST, 15, REST, 17, REST, 19, REST,
        17, REST, 15, REST, 14, REST, 12, REST, 10, REST, 8, REST, 7, REST, 5, REST,
    ],
    drums: &[
        Kick, Silent, Hat, Silent, Snare, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Snare, Silent, Hat, Hat,
    ],
};
pub const DESCENT: SongSpec = SongSpec {
    name: "Descent",
    root: 36.71, // D1
    scale: PHRYGIAN,
    bpm: 132.0,
    steps_per_beat: 4,
    bass_wave: Wave::Square,
    lead_wave: Wave::Sawtooth,
    pad_wave: Wave::Sawtooth,
    arp_wave: Wave::Square,
    sections: &[
        DESCENT_INTRO,
        DESCENT_VERSE,
        DESCENT_VERSE,
        DESCENT_REFRAIN,
        DESCENT_VERSE,
        DESCENT_BRIDGE,
        DESCENT_REFRAIN,
        DESCENT_REFRAIN,
    ],
    intensity: 0.85,
};

// ---- blood_rush.json: "Blood Rush" -------------------------------------------------------------
//
// SONG 5 — "Blood Rush" (AGGRESSIVE): feverish, blood-in-the-eyes rush. F#
// harmonic minor, jagged saw bass, wailing square lead over a stabbing arp.

const BLOOD_RUSH_INTRO: Section = Section {
    label: "intro",
    bass: &[0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST, 4, REST, 6, REST],
    lead: &[
        REST, REST, REST, REST, REST, REST, 11, REST, REST, REST, REST, REST, REST, REST, 12, REST,
        REST, REST, REST, REST, REST, REST, 14, REST, REST, REST, REST, REST, REST, REST, 11, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        7, 9, 11, 9, 7, 9, 11, 14, 7, 9, 11, 9, 11, 9, 7, 4,
        7, 9, 11, 9, 7, 9, 11, 14, 7, 9, 11, 9, 11, 9, 7, 4,
    ],
    drums: &[
        Kick, Hat, Snare, Hat, Kick, Silent, Snare, Hat, Kick, Hat, Snare, Hat, Kick, Silent, Snare, Hat,
    ],
};
const BLOOD_RUSH_VERSE: Section = Section {
    label: "verse",
    bass: &[0, 0, REST, 0, 6, REST, 0, 0, 0, 0, REST, 0, 4, REST, 6, REST],
    lead: &[
        11, REST, 12, 11, 9, REST, 11, REST, 12, REST, 14, 12, 11, 9, 11, REST,
        12, REST, 14, 12, 11, REST, 12, REST, 14, REST, 16, 14, 12, 11, 9, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, 6, REST, REST, REST],
    arp: &[
        7, 9, 11, 9, 7, 9, 11, 14, 7, 9, 11, 9, 11, 9, 7, 4,
        9, 11, 14, 11, 9, 11, 14, 16, 9, 11, 14, 11, 14, 11, 9, 7,
    ],
    drums: &[
        Kick, Hat, Snare, Hat, Kick, Kick, Snare, Hat, Kick, Hat, Snare, Hat, Kick, Snare, Snare, Hat,
    ],
};
const BLOOD_RUSH_REFRAIN: Section = Section {
    label: "refrain",
    bass: &[0, 0, 0, 0, 6, 6, 0, 0, 0, 0, 0, 0, 4, 4, 6, 6],
    lead: &[
        14, REST, 16, 14, 12, REST, 14, REST, 16, REST, 18, 16, 14, 12, 11, REST,
        16, REST, 18, 16, 14, REST, 16, REST, 18, REST, 19, 18, 16, 14, 12, REST,
    ],
    pad: &[4, REST, REST, REST, REST, REST, REST, REST, 6, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        11, 14, 16, 14, 11, 14, 16, 19, 11, 14, 16, 14, 16, 14, 11, 7,
        14, 16, 19, 16, 14, 16, 19, 21, 14, 16, 19, 16, 19, 16, 14, 11,
    ],
    drums: &[
        Kick, Kick, Snare, Hat, Kick, Kick, Snare, Kick, Kick, Kick, Snare, Hat, Kick, Snare, Snare, Snare,
    ],
};
const BLOOD_RUSH_BRIDGE: Section = Section {
    label: "bridge",
    bass: &[4, REST, REST, REST, 4, REST, REST, REST, 6, REST, REST, REST, 6, REST, REST, REST],
    lead: &[
        REST, REST, 12, 11, 9, REST, REST, REST, REST, REST, 11, 9, 7, REST, REST, REST,
        REST, REST, 14, 12, 11, REST, REST, REST, REST, REST, 12, 11, 9, REST, REST, REST,
    ],
    pad: &[4, REST, REST, REST, REST, REST, REST, REST, 6, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        7, 9, 11, 9, 7, 9, 11, 14, 7, 9, 11, 9, 11, 9, 7, 4,
        11, 9, 7, 9, 11, 14, 11, 9, 7, 9, 11, 9, 7, 4, 2, 0,
    ],
    drums: &[
        Kick, Silent, Snare, Silent, Kick, Silent, Snare, Silent, Kick, Hat, Snare, Hat, Kick, Hat, Snare, Hat,
    ],
};
pub const BLOOD_RUSH: SongSpec = SongSpec {
    name: "Blood Rush",
    root: 46.25, // F#1
    scale: HARMONIC_MINOR,
    bpm: 140.0,
    steps_per_beat: 4,
    bass_wave: Wave::Sawtooth,
    lead_wave: Wave::Square,
    pad_wave: Wave::Sawtooth,
    arp_wave: Wave::Sawtooth,
    sections: &[
        BLOOD_RUSH_INTRO,
        BLOOD_RUSH_VERSE,
        BLOOD_RUSH_VERSE,
        BLOOD_RUSH_REFRAIN,
        BLOOD_RUSH_VERSE,
        BLOOD_RUSH_BRIDGE,
        BLOOD_RUSH_REFRAIN,
        BLOOD_RUSH_REFRAIN,
    ],
    intensity: 0.95,
};

// ---- deep_static.json: "Deep Static" -----------------------------------------------------------
//
// SONG 6 — "Deep Static" (AGGRESSIVE): menacing deep-floor pressure. E
// Phrygian-dominant, relentless saw sub-bass in 16ths, dissonant stabs.

const DEEP_STATIC_INTRO: Section = Section {
    label: "intro",
    bass: &[0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST, 4, REST, 1, 0],
    lead: &[
        REST, REST, REST, REST, REST, REST, 7, REST, REST, REST, REST, REST, REST, REST, 8, REST,
        REST, REST, REST, REST, REST, REST, 7, REST, REST, REST, REST, REST, REST, REST, 11, REST,
    ],
    pad: &[0, REST, REST, REST, 1, REST, REST, REST, 0, REST, REST, REST, 4, REST, REST, REST],
    arp: &[
        REST, 14, 15, REST, 14, REST, 18, REST, REST, 14, 15, REST, 18, REST, 15, 14,
        REST, 14, 15, REST, 14, REST, 18, REST, REST, 14, 15, REST, 18, REST, 15, 14,
    ],
    drums: &[
        Kick, Silent, Kick, Silent, Snare, Silent, Kick, Silent, Kick, Silent, Kick, Silent, Snare, Silent, Kick, Silent,
    ],
};
const DEEP_STATIC_VERSE: Section = Section {
    label: "verse",
    bass: &[0, 0, 0, REST, 1, REST, 0, REST, 0, 0, 0, REST, 4, REST, 1, 0],
    lead: &[
        REST, REST, 7, REST, 8, REST, REST, 7, REST, 11, REST, REST, 8, REST, 7, REST,
        REST, REST, 8, REST, 7, REST, REST, 8, REST, 11, REST, REST, 7, REST, 8, REST,
    ],
    pad: &[0, REST, REST, REST, 1, REST, REST, REST, 0, REST, REST, REST, 4, REST, REST, REST],
    arp: &[
        REST, 14, 15, REST, 14, REST, 18, REST, REST, 14, 15, REST, 18, REST, 15, 14,
        14, REST, 15, REST, 18, REST, 15, REST, 14, REST, 18, REST, 21, REST, 18, 15,
    ],
    drums: &[
        Kick, Silent, Kick, Silent, Snare, Silent, Kick, Kick, Kick, Silent, Kick, Silent, Snare, Hat, Kick, Snare,
    ],
};
const DEEP_STATIC_REFRAIN: Section = Section {
    label: "refrain",
    bass: &[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 4, 4, 1, 0],
    lead: &[
        11, REST, 8, REST, 7, REST, 8, REST, 11, REST, 12, REST, 11, REST, 8, REST,
        14, REST, 11, REST, 8, REST, 7, REST, 8, REST, 11, REST, 14, REST, 11, REST,
    ],
    pad: &[4, REST, REST, REST, 1, REST, REST, REST, 0, REST, REST, REST, 4, REST, REST, REST],
    arp: &[
        14, 15, 18, 15, 14, 15, 18, 21, 14, 15, 18, 15, 18, 15, 14, 11,
        18, 15, 14, 15, 18, 21, 18, 15, 14, 15, 18, 21, 22, 21, 18, 15,
    ],
    drums: &[
        Kick, Kick, Kick, Snare, Snare, Kick, Kick, Kick, Kick, Kick, Kick, Snare, Snare, Kick, Kick, Snare,
    ],
};
const DEEP_STATIC_BRIDGE: Section = Section {
    label: "bridge",
    bass: &[4, REST, REST, REST, 4, REST, REST, REST, 1, REST, REST, REST, 1, REST, REST, REST],
    lead: &[
        REST, REST, 8, REST, 7, REST, REST, REST, REST, REST, 11, REST, 8, REST, REST, REST,
        REST, REST, 7, REST, 8, REST, REST, REST, REST, REST, 11, REST, 12, REST, REST, REST,
    ],
    pad: &[4, REST, REST, REST, REST, REST, REST, REST, 1, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        REST, 14, 15, REST, 14, REST, 18, REST, REST, 14, 15, REST, 18, REST, 15, 14,
        18, REST, 15, REST, 14, REST, 11, REST, 8, REST, 7, REST, 4, REST, 1, REST,
    ],
    drums: &[
        Kick, Silent, Silent, Silent, Snare, Silent, Kick, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Kick, Kick,
    ],
};
pub const DEEP_STATIC: SongSpec = SongSpec {
    name: "Deep Static",
    root: 41.2, // E1
    scale: PHRYGIAN_DOMINANT,
    bpm: 144.0,
    steps_per_beat: 4,
    bass_wave: Wave::Sawtooth,
    lead_wave: Wave::Sawtooth,
    pad_wave: Wave::Sawtooth,
    arp_wave: Wave::Square,
    sections: &[
        DEEP_STATIC_INTRO,
        DEEP_STATIC_VERSE,
        DEEP_STATIC_VERSE,
        DEEP_STATIC_REFRAIN,
        DEEP_STATIC_VERSE,
        DEEP_STATIC_BRIDGE,
        DEEP_STATIC_REFRAIN,
        DEEP_STATIC_REFRAIN,
    ],
    intensity: 1.0,
};

// ---- static_prayer.json: "Static Prayer" -------------------------------------------------------
//
// SONG 7 — "Static Prayer" (WAVY): a crawling, hopeless dirge. G Locrian
// (tritone), slow lurching bass, mournful pad drone, sparse detuned wails.

const STATIC_PRAYER_INTRO: Section = Section {
    label: "intro",
    bass: &[0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST],
    lead: &[
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        REST, REST, REST, REST, REST, REST, 14, REST, REST, REST, REST, REST, REST, REST, 15, REST,
        REST, REST, REST, REST, REST, REST, 18, REST, REST, REST, REST, REST, REST, REST, 15, REST,
    ],
    drums: &[
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Silent, Silent, Hat, Silent,
    ],
};
const STATIC_PRAYER_VERSE: Section = Section {
    label: "verse",
    bass: &[0, REST, REST, REST, 0, REST, REST, 4, 0, REST, REST, REST, 1, REST, REST, REST],
    lead: &[
        REST, REST, REST, REST, 8, REST, REST, REST, REST, REST, 7, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, 7, REST, REST, REST, REST, REST, 8, REST, REST, REST, REST, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        REST, REST, 14, REST, REST, REST, 15, REST, REST, REST, 18, REST, REST, REST, 15, REST,
        REST, REST, 15, REST, REST, REST, 18, REST, REST, REST, 14, REST, REST, REST, 11, REST,
    ],
    drums: &[
        Kick, Silent, Silent, Silent, Silent, Silent, Snare, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Hat, Silent,
    ],
};
const STATIC_PRAYER_REFRAIN: Section = Section {
    label: "refrain",
    bass: &[0, REST, REST, REST, 4, REST, REST, REST, 1, REST, REST, REST, 4, REST, REST, REST],
    lead: &[
        8, REST, REST, REST, 7, REST, REST, REST, 8, REST, REST, REST, 11, REST, REST, REST,
        12, REST, REST, REST, 11, REST, REST, REST, 8, REST, REST, REST, 7, REST, REST, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, 1, REST, REST, REST],
    arp: &[
        REST, 14, REST, 15, REST, 18, REST, 15, REST, 14, REST, 15, REST, 18, REST, 21,
        REST, 18, REST, 15, REST, 14, REST, 11, REST, 14, REST, 15, REST, 18, REST, 15,
    ],
    drums: &[
        Kick, Silent, Silent, Snare, Silent, Silent, Snare, Silent, Kick, Silent, Silent, Snare, Silent, Silent, Hat, Snare,
    ],
};
const STATIC_PRAYER_BRIDGE: Section = Section {
    label: "bridge",
    bass: &[4, REST, REST, REST, REST, REST, REST, REST, 1, REST, REST, REST, REST, REST, REST, REST],
    lead: &[
        REST, REST, REST, REST, REST, REST, REST, REST, 11, REST, REST, REST, 8, REST, 7, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, 12, REST, REST, REST, 11, REST, 8, REST,
    ],
    pad: &[4, REST, REST, REST, REST, REST, REST, REST, 1, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        REST, REST, 14, REST, REST, REST, 15, REST, REST, REST, 18, REST, REST, REST, 21, REST,
        REST, REST, 18, REST, REST, REST, 15, REST, REST, REST, 14, REST, REST, REST, 11, REST,
    ],
    drums: &[
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent,
    ],
};
pub const STATIC_PRAYER: SongSpec = SongSpec {
    name: "Static Prayer",
    root: 49.0, // G1
    scale: LOCRIAN,
    bpm: 92.0,
    steps_per_beat: 4,
    bass_wave: Wave::Sawtooth,
    lead_wave: Wave::Triangle,
    pad_wave: Wave::Sawtooth,
    arp_wave: Wave::Triangle,
    sections: &[
        STATIC_PRAYER_INTRO,
        STATIC_PRAYER_VERSE,
        STATIC_PRAYER_VERSE,
        STATIC_PRAYER_REFRAIN,
        STATIC_PRAYER_VERSE,
        STATIC_PRAYER_BRIDGE,
        STATIC_PRAYER_REFRAIN,
        STATIC_PRAYER_REFRAIN,
    ],
    intensity: 0.8,
};

// ---- mask_of_dread.json: "Mask of Dread" -------------------------------------------------------
//
// SONG 8 — "Mask of Dread" (AGGRESSIVE / heavy BOSS): dread-filled and huge. C
// Locrian (flat 2nd + tritone), slow but crushing; sustained saw bass lurching
// to the tritone, high square wails, enormous slow kicks. The mask watches.

const MASK_OF_DREAD_INTRO: Section = Section {
    label: "intro",
    bass: &[0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST],
    lead: &[
        7, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        8, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        REST, REST, 14, REST, 15, REST, REST, REST, REST, REST, 18, REST, 15, REST, 14, REST,
        REST, REST, 14, REST, 15, REST, REST, REST, REST, REST, 18, REST, 15, REST, 14, REST,
    ],
    drums: &[
        Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent,
    ],
};
const MASK_OF_DREAD_VERSE: Section = Section {
    label: "verse",
    bass: &[0, REST, REST, REST, 0, REST, 4, REST, 0, REST, REST, REST, 4, REST, 3, REST],
    lead: &[
        7, REST, REST, REST, REST, REST, REST, REST, 8, REST, REST, REST, REST, REST, 11, REST,
        REST, REST, REST, REST, 7, REST, REST, REST, 8, REST, REST, REST, REST, REST, 4, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        REST, REST, 14, REST, 15, REST, REST, REST, REST, REST, 18, REST, 15, REST, 14, REST,
        REST, REST, 15, REST, 18, REST, REST, REST, REST, REST, 14, REST, 11, REST, 14, REST,
    ],
    drums: &[
        Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent, Kick, Silent, Silent, Kick, Snare, Silent, Snare, Silent,
    ],
};
const MASK_OF_DREAD_REFRAIN: Section = Section {
    label: "refrain",
    bass: &[0, REST, 0, REST, 4, REST, 4, REST, 3, REST, 3, REST, 4, REST, 1, REST],
    lead: &[
        11, REST, REST, REST, 8, REST, REST, REST, 7, REST, REST, REST, 8, REST, 11, REST,
        12, REST, REST, REST, 11, REST, REST, REST, 8, REST, REST, REST, 7, REST, 4, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 4, REST, REST, REST, 1, REST, REST, REST],
    arp: &[
        14, REST, 15, REST, 18, REST, 15, REST, 14, REST, 15, REST, 18, REST, 21, REST,
        18, REST, 15, REST, 14, REST, 11, REST, 14, REST, 15, REST, 18, REST, 15, REST,
    ],
    drums: &[
        Kick, Silent, Kick, Silent, Snare, Silent, Kick, Silent, Kick, Silent, Kick, Kick, Snare, Silent, Snare, Snare,
    ],
};
const MASK_OF_DREAD_BRIDGE: Section = Section {
    label: "bridge",
    bass: &[4, REST, REST, REST, REST, REST, REST, REST, 3, REST, REST, REST, REST, REST, REST, REST],
    lead: &[
        REST, REST, REST, REST, 8, REST, REST, REST, REST, REST, REST, REST, 7, REST, REST, REST,
        REST, REST, REST, REST, 11, REST, REST, REST, REST, REST, REST, REST, 8, REST, REST, REST,
    ],
    pad: &[4, REST, REST, REST, REST, REST, REST, REST, 3, REST, REST, REST, REST, REST, REST, REST],
    arp: &[
        REST, REST, 14, REST, REST, REST, 15, REST, REST, REST, 18, REST, REST, REST, 21, REST,
        REST, REST, 18, REST, REST, REST, 15, REST, REST, REST, 14, REST, REST, REST, 11, REST,
    ],
    drums: &[
        Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent,
    ],
};
pub const MASK_OF_DREAD: SongSpec = SongSpec {
    name: "Mask of Dread",
    root: 32.7, // C1
    scale: LOCRIAN,
    bpm: 100.0,
    steps_per_beat: 4,
    bass_wave: Wave::Sawtooth,
    lead_wave: Wave::Square,
    pad_wave: Wave::Sawtooth,
    arp_wave: Wave::Square,
    sections: &[
        MASK_OF_DREAD_INTRO,
        MASK_OF_DREAD_VERSE,
        MASK_OF_DREAD_VERSE,
        MASK_OF_DREAD_REFRAIN,
        MASK_OF_DREAD_VERSE,
        MASK_OF_DREAD_BRIDGE,
        MASK_OF_DREAD_REFRAIN,
        MASK_OF_DREAD_REFRAIN,
    ],
    intensity: 1.15,
};

// ---- razor_circuit.json: "Razor Circuit" -------------------------------------------------------
//
// SONG 9 — "Razor Circuit" (AGGRESSIVE, audition candidate): driving darksynth
// combat. E natural minor, 126 BPM. Four-on-the-floor kick against pure
// offbeat square bass (the classic synthwave pump), a relentless 16th arp
// cycling the chord tones, and a hook lead that only arrives once the groove
// has earned it. One chord per bar, i - VI - III - VII (Em - C - G - D).
// Form: intro x2 (8 bars, arp teases in) -> groove x2 -> hook x2 ->
// breakdown -> groove -> hook x2. Sections are 4 bars (64 steps).
//
// pattern razor_pad: Chord bed shared by intro / groove / hook: one low triad on
// beats 1 and 3 of each bar, walking Em / C / G / D (pad degrees 0 / 5 / 2 / 6).
//
// pattern razor_bass_groove: The groove/hook bass: quarter-note OFFBEATS only
// (steps 2/6/10/14 of each bar) so the four-on-the-floor kick and the bass
// alternate — the pump. Roots follow the chords an octave down: E1 / C1 / G1 /
// D1 (0 / -2 / 2 / -1), with a doubled 16th turnaround at the end of bar 4.
//
// pattern razor_arp: The 16th-note arp: an up-down cycle of each bar's chord
// tones one to two octaves up (Em 7-9-11-14, C 12-14-16-19, G 9-11-13-16, D
// 13-15-17-20).

const RAZOR_CIRCUIT_PAT_RAZOR_PAD: &[i32] = &[
    0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST,
    5, REST, REST, REST, REST, REST, REST, REST, 5, REST, REST, REST, REST, REST, REST, REST,
    2, REST, REST, REST, REST, REST, REST, REST, 2, REST, REST, REST, REST, REST, REST, REST,
    6, REST, REST, REST, REST, REST, REST, REST, 6, REST, REST, REST, REST, REST, REST, REST,
];
const RAZOR_CIRCUIT_PAT_RAZOR_BASS_GROOVE: &[i32] = &[
    REST, REST, 0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST, 0, REST,
    REST, REST, -2, REST, REST, REST, -2, REST, REST, REST, -2, REST, REST, REST, -2, REST,
    REST, REST, 2, REST, REST, REST, 2, REST, REST, REST, 2, REST, REST, REST, 2, REST,
    REST, REST, -1, REST, REST, REST, -1, REST, REST, REST, -1, REST, -1, REST, -1, -1,
];
const RAZOR_CIRCUIT_PAT_RAZOR_ARP: &[i32] = &[
    7, 9, 11, 14, 11, 9, 7, 9, 7, 9, 11, 14, 11, 9, 7, 9,
    12, 14, 16, 19, 16, 14, 12, 14, 12, 14, 16, 19, 16, 14, 12, 14,
    9, 11, 13, 16, 13, 11, 9, 11, 9, 11, 13, 16, 13, 11, 9, 11,
    13, 15, 17, 20, 17, 15, 13, 15, 13, 15, 17, 20, 17, 15, 13, 15,
];
const RAZOR_CIRCUIT_INTRO: Section = Section {
    label: "intro",
    bass: &[
        0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST,
        -2, REST, REST, REST, REST, REST, REST, REST, -2, REST, REST, REST, REST, REST, REST, REST,
        2, REST, REST, REST, REST, REST, REST, REST, 2, REST, REST, REST, REST, REST, REST, REST,
        -1, REST, REST, REST, REST, REST, REST, REST, -1, REST, REST, REST, REST, REST, REST, REST,
    ],
    lead: &[REST],
    pad: RAZOR_CIRCUIT_PAT_RAZOR_PAD,
    arp: &[
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        9, 11, 13, 16, 13, 11, 9, 11, 9, 11, 13, 16, 13, 11, 9, 11,
        13, 15, 17, 20, 17, 15, 13, 15, 13, 15, 17, 20, 17, 15, 13, 15,
    ],
    drums: &[
        Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent,
        Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent,
        Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent,
        Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Hat, Hat,
    ],
};
const RAZOR_CIRCUIT_GROOVE: Section = Section {
    label: "groove",
    bass: RAZOR_CIRCUIT_PAT_RAZOR_BASS_GROOVE,
    lead: &[REST],
    pad: RAZOR_CIRCUIT_PAT_RAZOR_PAD,
    arp: RAZOR_CIRCUIT_PAT_RAZOR_ARP,
    drums: &[
        Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Hat, Hat,
    ],
};
const RAZOR_CIRCUIT_HOOK: Section = Section {
    label: "hook",
    bass: RAZOR_CIRCUIT_PAT_RAZOR_BASS_GROOVE,
    lead: &[
        18, REST, REST, 18, REST, 16, REST, 14, REST, REST, 16, REST, 14, REST, REST, REST,
        19, REST, REST, 19, REST, 16, REST, 14, REST, REST, 16, REST, 14, REST, REST, REST,
        20, REST, REST, 20, REST, 18, REST, 16, REST, REST, 18, REST, 16, REST, REST, REST,
        21, REST, REST, 20, REST, 18, REST, 17, REST, 15, REST, 17, REST, 18, REST, REST,
    ],
    pad: RAZOR_CIRCUIT_PAT_RAZOR_PAD,
    arp: RAZOR_CIRCUIT_PAT_RAZOR_ARP,
    drums: &[
        Kick, Silent, Hat, Silent, Kick, Silent, Snare, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Snare, Silent,
        Kick, Silent, Hat, Silent, Kick, Silent, Snare, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Snare, Silent,
        Kick, Silent, Hat, Silent, Kick, Silent, Snare, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Snare, Silent,
        Kick, Silent, Hat, Silent, Kick, Silent, Snare, Silent, Kick, Silent, Snare, Silent, Kick, Snare, Snare, Snare,
    ],
};
const RAZOR_CIRCUIT_BREAKDOWN: Section = Section {
    label: "breakdown",
    bass: &[
        0, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        0, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        -2, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        -1, REST, REST, REST, REST, REST, REST, REST, -1, REST, REST, REST, -1, REST, -1, -1,
    ],
    lead: &[
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, 18, REST, REST, 16, REST, 14, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, 14, REST, 16, REST, 18, REST, 21, REST,
    ],
    pad: &[
        0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST,
        0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST,
        5, REST, REST, REST, REST, REST, REST, REST, 5, REST, REST, REST, REST, REST, REST, REST,
        6, REST, REST, REST, REST, REST, REST, REST, 6, REST, REST, REST, REST, REST, REST, REST,
    ],
    arp: &[
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        12, 14, 16, 19, 16, 14, 12, 14, 12, 14, 16, 19, 16, 14, 12, 14,
        13, 15, 17, 20, 17, 15, 13, 15, 13, 15, 17, 20, 17, 15, 13, 15,
    ],
    drums: &[
        Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent,
        Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent, Silent, Silent, Hat, Silent,
        Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent, Kick, Silent, Hat, Silent,
        Kick, Silent, Hat, Silent, Kick, Silent, Snare, Silent, Kick, Silent, Snare, Silent, Kick, Snare, Snare, Snare,
    ],
};
pub const RAZOR_CIRCUIT: SongSpec = SongSpec {
    name: "Razor Circuit",
    root: 41.2, // E1
    scale: MINOR,
    bpm: 126.0,
    steps_per_beat: 4,
    bass_wave: Wave::Square,
    lead_wave: Wave::Sawtooth,
    pad_wave: Wave::Sawtooth,
    arp_wave: Wave::Square,
    sections: &[
        RAZOR_CIRCUIT_INTRO,
        RAZOR_CIRCUIT_INTRO,
        RAZOR_CIRCUIT_GROOVE,
        RAZOR_CIRCUIT_GROOVE,
        RAZOR_CIRCUIT_HOOK,
        RAZOR_CIRCUIT_HOOK,
        RAZOR_CIRCUIT_BREAKDOWN,
        RAZOR_CIRCUIT_GROOVE,
        RAZOR_CIRCUIT_HOOK,
        RAZOR_CIRCUIT_HOOK,
    ],
    intensity: 0.9,
};

// ---- cold_storage.json: "Cold Storage" ---------------------------------------------------------
//
// SONG 10 — "Cold Storage" (WAVY, audition candidate): slow cold menace for
// tense floors. C# natural minor, 78 BPM. A pedal-tone saw bass and a
// retriggered low pad drone hold the root while a 12-step (dotted-8th) sine
// motif — C#, G#, D# (the major 9th) — phases 3-against-4 over the bar,
// realigning every 3 bars. The "veil" sections shift the pad up one scale
// step (degree 1: D#-F#-A# over the C# pedal = the m9/m11 wash); "sink"
// finally moves the harmony i - i - VI - VII. Long arcs, sparse drums.
//
// pattern cold_bass_pedal: Heartbeat pedal on the tonic: beat 1, the "and" of 2,
// and beat 3.
//
// pattern cold_pad_drone: The drone bed: the i triad retriggered every beat so
// the slow pad attacks overlap into a continuous low wash.
//
// pattern cold_motif: The 3-against-4 motif: a 12-step lane (3 beats) looping
// inside 64-step (4-bar) sections — it drifts across the barline and realigns
// every 3 bars. Pitches C#3 / G#3 / D#3: degree 8 is the major 9th, the color
// note.

const COLD_STORAGE_PAT_COLD_BASS_PEDAL: &[i32] = &[0, REST, REST, REST, REST, REST, 0, REST, 0, REST, REST, REST, REST, REST, REST, REST];
const COLD_STORAGE_PAT_COLD_PAD_DRONE: &[i32] = &[0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST];
const COLD_STORAGE_PAT_COLD_MOTIF: &[i32] = &[7, REST, REST, 11, REST, REST, 8, REST, REST, 11, REST, REST];
const COLD_STORAGE_DRIFT: Section = Section {
    label: "drift",
    bass: &[0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST],
    lead: &[
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, 9, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        8, REST, REST, REST, REST, REST, REST, REST, 7, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
    ],
    pad: &[0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST],
    arp: &[REST],
    drums: &[
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent,
        Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Silent,
    ],
};
const COLD_STORAGE_PULSE: Section = Section {
    label: "pulse",
    bass: COLD_STORAGE_PAT_COLD_BASS_PEDAL,
    lead: &[REST],
    pad: COLD_STORAGE_PAT_COLD_PAD_DRONE,
    arp: COLD_STORAGE_PAT_COLD_MOTIF,
    drums: &[
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Silent, Silent, Hat, Silent,
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Silent, Silent, Hat, Silent,
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Silent, Silent, Hat, Silent,
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Hat, Silent,
    ],
};
const COLD_STORAGE_VEIL: Section = Section {
    label: "veil",
    bass: COLD_STORAGE_PAT_COLD_BASS_PEDAL,
    lead: &[
        9, REST, REST, REST, REST, REST, REST, REST, 8, REST, REST, REST, REST, REST, REST, REST,
        7, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, 10, REST, REST, REST, REST, REST, REST, REST, 9, REST, REST, REST,
        8, REST, REST, REST, REST, REST, REST, REST, 7, REST, REST, REST, REST, REST, REST, REST,
    ],
    pad: &[
        0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST,
        0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST, 0, REST, REST, REST,
        1, REST, REST, REST, 1, REST, REST, REST, 1, REST, REST, REST, 1, REST, REST, REST,
        1, REST, REST, REST, 1, REST, REST, REST, 1, REST, REST, REST, 1, REST, REST, REST,
    ],
    arp: COLD_STORAGE_PAT_COLD_MOTIF,
    drums: &[
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Hat, Silent,
    ],
};
const COLD_STORAGE_SINK: Section = Section {
    label: "sink",
    bass: &[
        0, REST, REST, REST, REST, REST, 0, REST, 0, REST, REST, REST, REST, REST, REST, REST,
        0, REST, REST, REST, REST, REST, 0, REST, 0, REST, REST, REST, REST, REST, REST, REST,
        5, REST, REST, REST, REST, REST, 5, REST, 5, REST, REST, REST, REST, REST, REST, REST,
        6, REST, REST, REST, REST, REST, 6, REST, 6, REST, REST, REST, REST, REST, REST, REST,
    ],
    lead: &[
        REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST, REST,
        REST, REST, REST, REST, REST, REST, REST, REST, 9, REST, REST, REST, 8, REST, REST, REST,
        12, REST, REST, REST, REST, REST, REST, REST, 11, REST, REST, REST, REST, REST, REST, REST,
        13, REST, REST, REST, REST, REST, REST, REST, 14, REST, REST, REST, REST, REST, REST, REST,
    ],
    pad: &[
        0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST,
        0, REST, REST, REST, REST, REST, REST, REST, 0, REST, REST, REST, REST, REST, REST, REST,
        5, REST, REST, REST, REST, REST, REST, REST, 5, REST, REST, REST, REST, REST, REST, REST,
        6, REST, REST, REST, REST, REST, REST, REST, 6, REST, REST, REST, REST, REST, REST, REST,
    ],
    arp: COLD_STORAGE_PAT_COLD_MOTIF,
    drums: &[
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent,
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent,
        Kick, Silent, Silent, Silent, Silent, Silent, Silent, Silent, Kick, Silent, Silent, Silent, Snare, Silent, Silent, Silent,
        Kick, Silent, Silent, Silent, Silent, Silent, Snare, Silent, Kick, Silent, Kick, Silent, Snare, Silent, Snare, Silent,
    ],
};
pub const COLD_STORAGE: SongSpec = SongSpec {
    name: "Cold Storage",
    root: 34.65, // C#1
    scale: MINOR,
    bpm: 78.0,
    steps_per_beat: 4,
    bass_wave: Wave::Sawtooth,
    lead_wave: Wave::Triangle,
    pad_wave: Wave::Sawtooth,
    arp_wave: Wave::Sine,
    sections: &[
        COLD_STORAGE_DRIFT,
        COLD_STORAGE_PULSE,
        COLD_STORAGE_VEIL,
        COLD_STORAGE_PULSE,
        COLD_STORAGE_SINK,
        COLD_STORAGE_VEIL,
        COLD_STORAGE_SINK,
        COLD_STORAGE_DRIFT,
    ],
    intensity: 0.7,
};

/// Number of songs.
pub const SONG_COUNT: usize = 10;

/// Every song, in songs/index.json order (the `?viz` tracker's list; floors
/// pick theirs through `song_for_floor`).
pub const SONGS: &[SongSpec; SONG_COUNT] = &[
    INSERT_COIN,
    NEON_LOUNGE,
    CHROME_VEINS,
    DESCENT,
    BLOOD_RUSH,
    DEEP_STATIC,
    STATIC_PRAYER,
    MASK_OF_DREAD,
    RAZOR_CIRCUIT,
    COLD_STORAGE,
];
