// Generate tests/fixtures/pose_plan.txt FROM web/robot-core.js's posePlan():
// the parity fixture the Rust port (src/render/pose.rs) is tested against
// (`cargo test matches_the_js_pose_plan`).
//
//   bun tools/gen_pose_fixture.ts           write the fixture   (make gen-pose)
//   bun tools/gen_pose_fixture.ts --check   fail if it is stale (make check-pose)
//
// Roadmap (docs/ARCHITECTURE.md): while the JS posePlan still drives the
// game, --check keeps the fixture honest; once the JS copy is deleted the
// fixture stays as the golden record of the behaviour that was ported.
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
// @ts-ignore — a plain ES module without types
import { posePlan, planFromScalars, POSES, POSE_SCALARS } from "../web/robot-core.js";

const OUT = join(import.meta.dir, "../tests/fixtures/pose_plan.txt");

// A fine grid over the first 0.7 s (the fall, the kick and both stomps all
// happen there), a coarse one out to 6 s (loops, the settled corpse), and a
// negative time (the finishers clamp it).
const times: number[] = [-0.1];
for (let i = 0; i <= 35; i++) times.push(i * 0.02);
for (let i = 1; i <= 17; i++) times.push(0.7 + i * 0.31);

// The SHORTEST decimal that round-trips the f32 the GPU rig would receive
// (at most 9 significant digits; `String(fround(v))` would print the 17 of
// the widened double).
const f32 = (v: number) => {
  const f = Math.fround(v || 0);
  for (let p = 1; p <= 9; p++) {
    const s = String(Number(f.toPrecision(p)));
    if (Math.fround(Number(s)) === f) return s;
  }
  return String(f);
};

const lines = [
  "# GENERATED by tools/gen_pose_fixture.ts from web/robot-core.js posePlan() — do not hand-edit.",
  // The column order IS `POSE_SCALARS` — the list the renderer unpacks the
  // ROBOT op with; the Rust test checks its own order against this header.
  `# pose relaxed time ${(POSE_SCALARS as string[]).join(" ")} shoot headless`,
];
for (const pose of POSES as string[]) {
  for (const relaxed of [false, true]) {
    for (const t of times) {
      const time = Math.fround(t); // the f32 the engine would send
      const p = posePlan(pose, time, relaxed);
      lines.push(
        [
          pose, relaxed ? 1 : 0, f32(time),
          ...(POSE_SCALARS as string[]).map((name) => f32(p[name])),
          p.shoot ? 1 : 0, p.headless ? 1 : 0,
        ].join(" "),
      );
    }
  }
}
const text = lines.join("\n") + "\n";

// The unpack the renderer uses must be the exact inverse of that column order
// (and of the flags): a plan packed by name comes back field for field.
{
  const src: Record<string, number | boolean> = { shoot: true, headless: true };
  (POSE_SCALARS as string[]).forEach((name, k) => (src[name] = k + 1));
  const packed = Float32Array.from((POSE_SCALARS as string[]).map((n) => src[n] as number));
  const back = planFromScalars({}, packed, 0, 3);
  for (const name of [...(POSE_SCALARS as string[]), "shoot", "headless"]) {
    if (back[name] !== src[name]) {
      console.error(`planFromScalars does not invert POSE_SCALARS: ${name} = ${back[name]}, want ${src[name]}`);
      process.exit(1);
    }
  }
  if (planFromScalars({}, packed, 0, 0).shoot || planFromScalars({}, packed, 0, 1).headless) {
    console.error("planFromScalars: flag bits are wrong (bit 0 = shoot, bit 1 = headless)");
    process.exit(1);
  }
}

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch {}
  if (current !== text) {
    console.error("tests/fixtures/pose_plan.txt is STALE vs web/robot-core.js posePlan() — run: make gen-pose");
    console.error("(and port the change to src/render/pose.rs: `cargo test matches_the_js_pose_plan`)");
    process.exit(1);
  }
  console.log(`pose fixture is current (${lines.length - 2} rows)`);
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT} (${lines.length - 2} rows)`);
}
